### ISSUE TITLE
Error installing RSDB package in R

### ISSUE THREAD

**Issue by adrianstrkr** [environmentalinformatics-marburg/rsdb#5]
Hello,

just tried to install the RSDB R-package using the code you published on this page:

if(!require("remotes")) install.packages("remotes")
remotes::install_github("environmentalinformatics-marburg/rsdb/r-package")
library(RSDB)

However I get the following error message:
Error in read.dcf(path) : 
  Found continuation line starting '    This R package c ...' at begin of record.

Am I doing something wrong, or is it a bug that needs a fix?

thanks for your help in advance!

Sincerly yours,

Adrian

**Comment by swoellauer** [comment]
Could not reproduce the issue.

It may be Windows style line-endings in "DESCRIPTION"-file. This is changed to Linux style on master now.

What version is your remotes package? Update to most current R-packages may resolve the issue. 
R.Version()
packageVersion("remotes")

Can you try again?
remotes::install_github("environmentalinformatics-marburg/rsdb/r-package", force = TRUE)

**Comment by swoellauer** [comment]
Issue did not occur again.

Restart of R environment may resolve that issue.
